---
- name: Basic Setup
  hosts: nextcloud
  become: yes
  tags:
    - base
  vars_files:
    - vars.yml
  roles:
    - base

- name: Nextcloud
  hosts: nextcloud
  become: yes
  vars_files:
    - vars.yml
  tags:
    - nextcloud
  vars:
    nginx_domain_name: "{{ main_domain }}"
  roles:
    - nginx
    - nginx-tls-add
    - nextcloud