---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user
  user:
    name: watchtower
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: docker
    state: present

- name: Ensure base / data directories for watchtower exist
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
  loop:
    - { path: "/srv/watchtower", owner: "watchtower" }      

- name: Ensure docker-compose.yml for watchtower
  template:
    src: docker-compose.j2
    dest: "/srv/watchtower/docker-compose.yml"

- name: Ensure environment file
  template:
    src: env.j2
    dest: "/srv/watchtower/.env"
