# Secure the server

- name: Disallow ssh password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify: Restart ssh

- name: Disallow root SSH access with passwords
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin prohibit-password"
    state=present
  notify: Restart ssh

- name: allow ssh in ufw
  ufw:
    rule: limit
    name: OpenSSH
    state: enabled
  notify: Restart ufw
