# Update lists and upgrade packages.
- name: update apt package lists
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: upgrade packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: install required packages
  apt:
    name: "{{ required_packages }}"
    state: latest
  when: required_packages|length

